theme_name: NewTheme
theme_version: 1.0

colors:
  primary: "#005b99"
  text: "#2e353f"
  text_light: "#4f5969"
  heading: "#1a202c"
  heading_black: "#black"
  accent: "#d1dce5"
  background: "#fff"
  light:
    primary: "#005b99"
    text: "#2e353f"
    text_light: "#4f5969"
    heading: "#1a202c"
    heading_black: "#black"
    accent: "#d1dce5"
    background: "#fff"
  dark:
    primary: "#fff"
    text: "#fff"
    text_light: "#fff"
    heading: "#fff"
    heading_black: "#fff"
    accent: "#fff"
    background: "#282C35"

font:
  fontWeight_bold: "700"
  fontWeight_black: "900"
  fontSize_root: "16px"