theme_name: NewTheme
theme_version: 1.0

lang: en

# colors:
#   primary: "#005b99"
#   text: "#2e353f"
#   text-light: "#4f5969"
#   heading: "#1a202c"
#   heading-black: "#black"
#   accent: "#d1dce5"